using System;

namespace rabbit_chat.Messages
{
    public class Message
    {
        /// <summary>
        /// Id of message
        /// </summary>
        public int Id;
        /// <summary>
        /// Id of user that sent message
        /// </summary>
        public int UserFromId;
        /// <summary>
        /// Id of user message is sent to
        /// </summary>
        public int UserToId;
        /// <summary>
        /// Id of content stored as JSON in DB
        /// </summary>
        public int ContentId;
        /// <summary>
        /// Id of room message was sent from
        /// </summary>
        public int RoomId;
        /// <summary>
        /// Username that sent message
        /// </summary>
        public string UserFromUsername;
        /// <summary>
        /// Username of user message is sent to
        /// </summary>
        public string UserToUsername;
        /// <summary>
        /// Content of message deserialized from JSON
        /// Should the message store the content, or merely the content id?
        /// </summary>
        public string Content;
        /// <summary>
        /// Time message was sent - generated by client
        /// </summary>
        public DateTime TimeSent;
    }
}